### ISSUE TITLE
Log in 

### ISSUE THREAD

**Issue by ramieb11** [MotivatedCreation/TutorMe#39]
Just to make it easier, I think when log in credentials are put in and user is ready to log in they should be able to press enter and log in automatically instead of always having to click log in

**Comment by richardBennett** [comment]
Oh man good luck. I've tried doing onsubmits or listening for an enter pressed in the password box but I can't get anything to work. I'll keep playing with it though.

**Comment by richardBennett** [comment]
I was able to get it working. I think something with bootstrap made it so the form didn't submit so I added a hidden submit button and now it works as intended.  Ugly but it works
