### ISSUE TITLE
Newly added Classes are not always displaying.

### ISSUE THREAD

**Issue by MotivatedCreation** [MotivatedCreation/TutorMe#4]
Newly added classes are not always displaying.
- Found by Bennett
- Occurs when the Enter button on the keyboard is pressed.

**Comment by MotivatedCreation** [comment]
This happens because the Cancel button event is triggered and not the Submit button event. We need to decide if the Cancel button event should be triggered or the Submit button event should be triggered when the Enter button on the keyboard is pressed.
- Group decision

**Comment by richardBennett** [comment]
This issue has been resolved. Classes are now added when enter is pressed (in my branch atm, I'll merge it later this weekend)
