### ISSUE TITLE
Teacher Assignments Delete

### ISSUE THREAD

**Issue by andersnf** [MotivatedCreation/TutorMe#8]
Once my piece is merged, the delete button for Teacher Assignments is not working.

**Comment by richardBennett** [comment]
I've got it working, but it leaves the page icon on the page until you leave

**Comment by richardBennett** [comment]
I've resolved this issue.
Deleting assignments doesn't work like class delete where it exists as long as there are people in the class. Deleting the assignment as the teacher now fully deletes the assignment.

To get around the page icon staying whenever an assignment was deleted I have it refresh the table like it does when you add an assignment.
